### PR TITLE
Create Review.txt

### PR DESCRIPTION
**Pull request by Shiva-Rz**
Hi Jeyandh,
Could you please review my file.

### CODE REVIEW

**Comment by Jeyandh** [comment]
Hi Shiva, 
The above code is good but i found some minor mistakes regarding coding standard. 
1) In bean class, You need to remove the unwanted white spaces between the code lines
2) In the same bean class give suitable name for variables.

**Comment by Shiva-Rz** [comment]
Thank you Jeyandh,
 I have changed the corrections as you mentioned above. Could you please verify it once again.

**Comment by Jeyandh** [comment]
In Controller you didn't give any white space between lines and also give one white space before parenthesis.

**Comment by Shiva-Rz** [comment]
Yes, I changed it now. Please verify it and share your review

**Comment by Jeyandh** [comment]
Yeah Shiva if you could please give some comments in coding so that anyone can understand easily. That's all Shiva. Thank you!!!

**Comment by Shiva-Rz** [comment]
Yes Jeyandh, I made the changes thank you for your review.
Thank you for your time

**Pull request merged**
